POST http://localhost:300/api/vi/users
Content-Type: application/json

{
    "name": "Jotakin",
    "username": "Taas Jotakin",
    "password": "salasana",
    "email": "email.longemail@email.com",
}
